CREATE TABLE "Ships" ("Id"	TEXT NOT NULL, "PlayerId" TEXT NOT NULL, "PicturePath" TEXT NOT NULL, "CargoSize" REAL NOT NULL,"Hull" 
INTEGER NOT NULL DEFAULT 3,"Shield"	INTEGER NOT NULL DEFAULT 3, "ShipState" INTEGER NOT NULL DEFAULT 0,	"Name" TEXT NOT NULL, 
PRIMARY KEY("Id"))